apiVersion: v2
name: logging-stack
description: "Logging stack including Loki, fluent-bit, and Grafana dashboards"
type: application
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: alexiscarbillet


dependencies:
  - name: fluent-bit
    version: "0.46.7"
    repository: "https://fluent.github.io/helm-charts"
  - name: loki
    version: "6.15.5"
    repository: "https://grafana.github.io/helm-charts"
  - name: grafana
    version: "8.3.5"
    repository: "https://grafana.github.io/helm-charts"
